/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DlcMarkdownEditor {
    'bold': () => Promise<void>;
    'content': string;
    'customElementSelector': string;
    'enableShortcuts': boolean;
    'h1': () => Promise<void>;
    'italics': () => Promise<void>;
    'link': () => Promise<void>;
    'setContent': (content: string) => Promise<void>;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLDlcMarkdownEditorElement extends Components.DlcMarkdownEditor, HTMLStencilElement {}
  var HTMLDlcMarkdownEditorElement: {
    prototype: HTMLDlcMarkdownEditorElement;
    new (): HTMLDlcMarkdownEditorElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'dlc-markdown-editor': HTMLDlcMarkdownEditorElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface DlcMarkdownEditor extends JSXBase.HTMLAttributes<HTMLDlcMarkdownEditorElement> {
    'content'?: string;
    'customElementSelector'?: string;
    'enableShortcuts'?: boolean;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'dlc-markdown-editor': DlcMarkdownEditor;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


